apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    tier: front
  name: vote
  namespace: instavote
spec:
  template:
    spec:
      containers:
        - image: schoolofdevops/vote:v5
          name: vote