# .github/workflows/test-github-dispatch-provider.yml
name: test-github-dispatch-provider
on:
  repository_dispatch:
    # this must exactly match the `event_type` you send below:
    types: [ "Kustomization/vote‑staging.flux‑system" ]

jobs:
  run-tests-staging:
    runs-on: ubuntu-latest      # ubuntu-18.04 is deprecated; switch to ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "running tests for dispatch type ${{ github.event.action }}…"
