name: test-github-dispatch-provider
on:
  repository_dispatch:
    types: [ Kustomization/vote-staging.flux-system ]
jobs:
  run-tests-staging:
    runs-on: ubuntu-18.04
    steps:
      - name: Run tests
        run: echo "running tests.."